version: '3.8'
services:
  mysqldb:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: "mysql"
    ports:
      - "3306:3306"
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  app:
    container_name: task-manager-api
    restart: always
    build: ./api
    ports:
      - 3333:3333
    environment:
      DB_HOST: task_manager
      DB_PORT: 3306
      DB_USER: "root"
      DB_PASSWORD: "mysql"
      DB_DATABASE: "task-manager"
    links:
      - mysqldb
    depends_on:
      - mysqldb